version: 2

references:
  default: &default
    docker:
      - image: cimg/go:1.17
  tag_filter_release: &tag_filter_release
     filters:
       tags:
         only:
           - /^v.*/
       branches:
         ignore: /.*/

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          name: "Restore cache: gomod"
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: "Collect Go Dependencies"
          command: |
            go version
            go mod tidy
            go mod verify
      - save_cache:
          name: "Save cache: gomod"
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: "Bulid macgyver binary for x86_64"
          environment:
            CGO_ENABLED: 0
            GOOS: linux
            GOARCH: amd64
          command: |
            go build -o macgyver main.go
      - save_cache:
          name: "Save cache: macgyver binary"
          key: macgyver-bin-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - macgyver
  release:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          name: "Restore cache: macgyver binary"
          key: macgyver-bin-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "Compress built macgyver binary"
          command: |
            tar zcvf macgyver.tar.gz macgyver
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: "Create release for macgyver"
          command: |
            tag=$(git tag -l --points-at HEAD)
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag macgyver.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - build:
          <<: *tag_filter_release
      - release:
          requires:
            - build
          <<: *tag_filter_release
